services:
  db:
    image: bitnami/postgresql
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: wallet_finance_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/bitnami/postgresql

volumes:
  db_data:
